# Generated by Django 4.2.5 on 2023-10-04 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 4, 23, 13, 49, 309804)),
        ),
        migrations.AlterField(
            model_name='author',
            name='designation',
            field=models.CharField(default='', max_length=50),
        ),
    ]
