# Generated by Django 4.2.5 on 2023-10-10 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_alter_article_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 10, 17, 26, 19, 251769)),
        ),
    ]
