# Generated by Django 4.2.5 on 2023-10-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(default=None)),
                ('pdf', models.FileField(blank=True, default='', null=True, upload_to='media/epaper')),
            ],
        ),
    ]
