# Generated by Django 4.2.5 on 2023-10-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epaper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='epaper',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/epaper/images'),
        ),
    ]
